# Generated by Django 5.2 on 2025-05-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coursesetter", "0002_alter_clickresult_game"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="clickresult",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="clickresult",
            name="game",
        ),
        migrations.RemoveField(
            model_name="clickresult",
            name="user",
        ),
        migrations.DeleteModel(
            name="GameRound",
        ),
        migrations.DeleteModel(
            name="ClickResult",
        ),
    ]
