# Generated by Django 5.2 on 2025-05-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("coursesetter", "0003_alter_clickresult_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="publishedFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255, unique=True)),
                ("published", models.BooleanField(default=False)),
            ],
        ),
    ]
