# Generated by Django 5.2 on 2025-05-16 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coursesetter", "0004_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="publishedFiles",
            new_name="publishedFile",
        ),
    ]
