# Generated by Django 5.2 on 2025-05-09 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("play", "0002_userresult_filename"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="userresult",
            index=models.Index(
                fields=["filename"], name="play_userre_filenam_90fcff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userresult",
            index=models.Index(
                fields=["control_pair_index"], name="play_userre_control_049165_idx"
            ),
        ),
    ]
